### PR TITLE
fix: Only enable TypeScript jsx compiling for `.js`, `.jsx`, and `.tsx` files

### LINKED ISSUE #44: Typescript compiler assumes JSX use
The Typescript compiler inside this repository always assumes a React context. This puts Typescript into a parsing mode of a `tsx` file context. This means valid Typescript syntax won't work if the file extension is a `.ts` file. Generics are treated JSX constructs in some cases.

- Operating System: Doesn't matter
- Cypress Version: 4.4.1
- Browser Version: Doesn't matter

Example:
```ts
const isKeyOf = <T>(obj: T, key: any): key is keyof T => {
  return typeof key === 'string' && key in obj;
}
```

Normally the file extension determines how the Typescript parser understands this. In normal Typescript code, the `<T>` is recognized as a generic. In JSX mode, it is recognized as a JSX element.

I traced it to this: https://github.com/cypress-io/cypress-browserify-preprocessor/pull/38/files#diff-efc83db4b84c72bbb60040a0125ad637R32-R37

The config sets `jsx` to `react`. This forces the Typescript parser to treat the string as a `tsx` file regardless of the original file extension.

Here's an example in the Typescript playground:
https://www.typescriptlang.org/play/#code/MYewdgzgLgBAlhA0gUwJ4HkBmMC8MA8AKgHwAUIARgFYBcMhANDANZp0CGYqAlHa6vAgs0IbIVzEYAbwBQMGACdkUAK4KwMKKgAOyUcIE4jMAOTQFcMAHMTMAGR2D8DZSoBuGQF8gA

In the config, the JSX is set to `none`. The output looks like:
```js
"use strict";
const isKeyOf = (obj, key) => {
    return typeof key === 'string' && key in obj;
};
```

If you change the JSX in the config to `react`, the output looks like:
```js
"use strict";
const isKeyOf = React.createElement(T, null,
    "(obj: T, key: any): key is keyof T => ",
,
    "return typeof key === 'string' && key in obj; }");
```

and the parser fails with an error.

### Is this a Feature or Bug?
Bug maybe? If the behavior cannot be fixed, it should at least be documented.

I wasn't sure how to fit info in the template or what the solution should be. Perhaps use the file extension to determine if the `jsx` config flag should be used. Also possibly use the Typescript config instead of a hard-coded one?

### PR DESCRIPTION
**Pull request by sainthkh**
Fixes #44.

### CODE REVIEW

File: lib/simple_tsify.js [hunk 1]
```diff
@@ -32,7 +34,7 @@ module.exports = function (b, opts) {
         this.push(ts.transpileModule(text, {
           compilerOptions: {
             esModuleInterop: true,
-            jsx: 'react',
+            jsx: ext === '.ts' ? undefined : 'react',
```
Comment (chrisbreiding) [inline lib/simple_tsify.js:37]: This makes the default `react` and only turns it off if the extension is `.ts`. I think it should be flipped, so it's only set to `react` if the extension is `.tsx` (maybe `.jsx` too? not sure if that makes sense or is necessary). Seems more future-proof, so if some framework `foo` creates a TypeScript-compatible extension `.tsf`, it doesn't switch to `react` mode.

File: test/fixtures/typescript/math_spec.ts [hunk 2]
```diff
@@ -5,6 +5,10 @@ const { add } = math
 
 const x: number = 3
 
+const isKeyOf = <T>(obj: T, key: any): key is keyof T => {
```
Comment (chrisbreiding) [inline test/fixtures/typescript/math_spec.ts:8]: Let's add a comment with a link to the issue above this to make it clear what this is testing:

```
// ensures that generics can be properly compiled and not treated
// as react components
// https://github.com/cypress-io/cypress-browserify-preprocessor/issues/44
```

File: lib/simple_tsify.js (hunk 1 above)
Comment (NicholasBoll) [reply lib/simple_tsify.js:37]: 'react' isn't the only option, but probably the most common. Should there be a way to configure this?

Comment (sainthkh) [reply lib/simple_tsify.js:37]: @chrisbreiding 

Then, how about changing it to `ext === '.js' || ext === '.jsx' || ext === '.tsx'`? Many developers use JSX syntax with `.js` files. I think it's safer to include `.js` files to the list. 

@NicholasBoll

There are 4 options: `undefined`, `"react"`, `"preserve"`, `"react-native"`. 

But `"preserve"` and `"react-native"` don't make sense here. Cypress transpiles the test code and sends it to the browser and runs it. When we select `"preserve"` or `"react-native"` option, the code cannot be executed on browsers. Because JSX is not compiled and they're still `<X />` in the transpiled code.

Currently, developers use `.js`, `.jsx`, `.tsx` extensions to include JSX syntax. And `.ts` doesn't allow JSX syntax. AFAIK, there is no other scenario. So, I don't think providing option to allow other `jsx` TypeScript compile options is an over-spec.

File: test/fixtures/typescript/math_spec.ts (hunk 2 above)
Comment (sainthkh) [reply test/fixtures/typescript/math_spec.ts:11]: Done.

File: lib/simple_tsify.js (hunk 1 above)
Comment (chrisbreiding) [reply lib/simple_tsify.js:37]: > Then, how about changing it to ext === '.js' || ext === '.jsx' || ext === '.tsx'

That sounds reasonable.
